### ISSUE TITLE
Intergration tests

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron-release-testing#2]
I have a notebook for doing integration tests pertaining to a [pull request](https://github.com/pyiron/pyiron/pull/463) I just made. The catch is that the current [place we read notebooks from](https://github.com/pyiron/pyiron/tree/master/notebooks) for automated release testing seems like the notebooks are all educational, and it would be weird to throw an integration test into the mix.

Could we create a sub-folder for integration tests, e.g. pyiron/notebooks/integration, and add that path to the automation here?

**Comment by jan-janssen** [comment]
@liamhuber I guess this question came up again recently as we had some trouble with the recent updates to the Sphinx parser. So I want to move this issue to the main pyiron repository to discuss it with some more people.
